import colorama
colorama.init(autoreset=True)
colorama.Style.NORMAL
print(colorama.Fore.BLACK+"Hello im BLACK") 
print(colorama.Fore.BLUE+"Hello im BLUE") 
print(colorama.Fore.CYAN+"Hello im CYAN") 
print(colorama.Fore.GREEN+"Hello im GREEN") 
print(colorama.Fore.LIGHTBLACK_EX+"Hello im LIGHTBLACK_EX") 
print(colorama.Fore.LIGHTBLUE_EX+"Hello im LIGHTBLUE_EX") 
print(colorama.Fore.LIGHTCYAN_EX+"Hello im LIGHTCYAN_EX") 
print(colorama.Fore.LIGHTGREEN_EX+"Hello im LIGHTGREEN_EX") 
print(colorama.Fore.LIGHTMAGENTA_EX+"Hello im LIGHTMAGENTA_EX") 
print(colorama.Fore.LIGHTRED_EX+"Hello im LIGHTRED_EX") 
print(colorama.Fore.LIGHTWHITE_EX+"Hello im LIGHTWHITE_EX") 
print(colorama.Fore.LIGHTYELLOW_EX+"Hello im LIGHTYELLOW_EX") 
print(colorama.Fore.MAGENTA+"Hello im MAGENTA") 
print(colorama.Fore.RED+"Hello im RED") 
print(colorama.Fore.RESET+"Hello im RESET") 
print(colorama.Fore.WHITE+"Hello im WHITE") 
print(colorama.Fore.YELLOW+"Hello im YELLOW") 
